#!/bin/bash
set -euo pipefail
set -x

server=${1?Please provide directory for server configuration.}

name=$(basename "$server")

# Delete if it already exists.
doctl compute droplet delete --force "$name" || true

udf=$(mktemp)
trap "rm -f '$udf'" EXIT
./user-data client.d "$server" >> "$udf"
cat "$udf"

droplet=$(doctl compute droplet create \
  --output json \
  --image "$(<"$server/image")" \
  --size "$(<"$server/size")" \
  --region "$(<"$server/region")" \
  --ssh-keys "$(<"$server/ssh-keys")" \
  --user-data-file "$udf" \
  "$name"
)

id=$(jq '.[0].id' <<<"$droplet")

while [[ $(doctl compute droplet get "$id" --output json | jq -r '.[0].status') != "active" ]]; do
  sleep 5
done

doctl compute floating-ip-action assign "$(<"$server/public.ip")" "$id"
