#!/bin/bash
set -euo pipefail

client=${1?Please provide directory for client configuration.}
server=${2?Please provide directory for server configuration.}

config=$(cat <<EOF
[Interface]
Address = $(<"$client/ip")/24
PrivateKey = $(<"$client/key")
DNS = $(<"$server/private.ip")

[Peer]
PublicKey = $(wg pubkey < "$server/key")
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = $(<"$server/public.ip"):51820
EOF
)

cat <<<"$config"
qrencode -t ansiutf8 <<<"$config" 1>&2
