#!/bin/bash
set -euo pipefail

clients=${1?Please provide directory for client configurations.}
server=${2?Please provide directory for server configuration.}

ip=$(<"$server/private.ip")

cat <<GEN
#!/bin/bash
set -euo pipefail
set -x

export DEBIAN_FRONTEND=noninteractive

apt-get update -y

# Install Wireguard Tooling
apt-get install -y wireguard

# Configure Traffic Forwarding
cat >> /etc/sysctl.conf <<EOF
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
EOF

sysctl -p

mkdir -p /etc/wireguard
cat >> /etc/wireguard/wg0.conf <<EOF
$(./server-config "$clients" "$server")
EOF

wg-quick up wg0
systemctl enable wg-quick@wg0.service

apt-get install -y unbound unbound-host
curl -o /var/lib/unbound/root.hints https://www.internic.net/domain/named.cache
chown -R unbound:unbound /var/lib/unbound

cat > /etc/unbound/unbound.conf <<EOF
server:
  num-threads: 4
  verbosity: 1

  root-hints: "/var/lib/unbound/root.hints"
  auto-trust-anchor-file: "/var/lib/unbound/root.key"

  interface: 0.0.0.0
  max-udp-size: 3072

  access-control: 0.0.0.0/0 refuse
  access-control: 127.0.0.1 allow
  access-control: $ip/24 allow

  private-address: $ip/24

  hide-identity: yes
  hide-version: yes

  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-referral-path: yes

  unwanted-reply-threshold: 10000000

  val-log-level: 1

  cache-min-ttl: 1800

  cache-max-ttl: 14400
  prefetch: yes
  prefetch-key: yes
EOF

systemctl disable systemd-resolved.service
systemctl stop systemd-resolved.service

cat > /etc/resolv.conf <<EOF
nameserver 127.0.0.1
options edns0
EOF

systemctl enable unbound
systemctl start unbound

# Needed to get it to bind the interfaces correctly apparently.
systemctl restart unbound
GEN
